#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains
# a custom header
#
balancer="\
frontend  cybergirls_frontend
frontend  http-cybergirls_frontend
        bind *:80
        mode http
        default_backend cybergirls_backend
backend cybergirls_backend
        balance roundrobin
        server 455920-web-01 54.209.6.159:80 check
        server 455920-web-02 54.158.207.61:80 check
"
# Update packages
apt-get -y update
apt-get -y upgrade

# Add HAProxy PPA
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.5
apt-get -y update

# Install HAProxy
apt-get -y install haproxy
cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$balancer" >> /etc/haproxy/haproxy.cfg
service haproxy restart
