#!/usr/bin/env bash
# Get the process ID (PID) of the Gunicorn master
pgrep gunicorn | xargs -n 1 kill -HUP
        location /static/ {
        alias /home/ubuntu/AirBnB_clone_v4/web_dynamic/static/;
    }
}
